// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/get-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/portfolio.ts
var profile = {
  name: "Sanket Tamboli",
  title: "Director of Delivery \u2014 Client Services",
  company: "Technocore360",
  location: "Vadodara, Gujarat, India",
  education: "Postgraduate in HRM",
  yearsOfExperience: 9,
  certifications: ["AI Product Management", "Scrum Master", "Lean Six Sigma"],
  summary: "Director of Delivery at Technocore360. Owns end-to-end execution for the client-services portfolio across US, Europe, Canada, and India, leading an 11-person team to SLA and fulfillment targets. Acts as internal product owner for the team's SaaS/ATS workflows \u2014 gathering feedback, prioritizing enhancements with vendors, validating releases, and enforcing clean-data standards. Delivered ServiceNow SOW engagements (ITSM/ITOM/HRSD/CSM), deploying 20+ consultants against fixed acceptance criteria and reducing time-to-fill on niche roles from 90 to 15 days. Defines delivery KPIs and dashboards (fill rate, ramp time, SLA adherence) that surface revenue leakage and inform leadership decisions.",
  positioning: "Operations to Product \u2014 a delivery leader transitioning into Product Manager / Product Owner roles.",
  resumeUrl: "https://drive.google.com/file/d/1zNr2cCp_NRRDGWJJ9yV-KMPQmqVUvrAV/view?usp=sharing"
};
var contact = {
  email: "sanket.130410111098@gmail.com",
  phone: "+91 9998271731",
  linkedin: "https://linkedin.com/in/sanket-tamboli",
  location: "Vadodara, Gujarat, India"
};
var experience = [
  {
    role: "Director of Delivery \u2014 Client Services",
    company: "Technocore360",
    period: "Apr 2026 \u2013 Present",
    current: true,
    focus: "Portfolio Owner",
    description: "Own end-to-end delivery across IT, healthcare, pharma, and technical-functional domains for local to Fortune 200 clients. Lead an 11-person team across India and US to SLA and fulfillment targets. Delivered ServiceNow SOW engagements (ITSM/ITOM/HRSD/CSM), cutting time-to-fill on niche roles from 90 to 15 days. Act as internal product owner for the team's SaaS/ATS workflows.",
    tags: ["Portfolio Ownership", "ServiceNow SOW", "KPI & Dashboards"]
  },
  {
    role: "Senior Manager \u2014 Operations & Delivery",
    company: "Technocore360",
    period: "Apr 2025 \u2013 Jun 2026",
    current: false,
    focus: "Platform Owner",
    description: "Ran daily operations and capacity planning for a 5\u20137 person team across India and US. Built revenue matrices and growth dashboards that surfaced leakages for leadership. Audited ATS process adherence, enforced clean-data standards, and led requirement gathering with hiring managers to reduce requirement churn.",
    tags: ["Backlog Ownership", "Revenue Dashboards", "Process Design"]
  },
  {
    role: "Associate Delivery Manager",
    company: "Technocore360",
    period: "Apr 2022 \u2013 Mar 2025",
    current: false,
    focus: "Team Lead",
    description: "Led US IT hiring for Fortune 500 clients and start-ups, managing a 10-member team. Owned recruitment metrics, modified procedures to resolve bottlenecks, and partnered with department heads to forecast hiring needs.",
    tags: ["Team Leadership", "Metrics Ownership", "Stakeholder Planning"]
  },
  {
    role: "Lead Recruitment Executive",
    company: "Diverse Lynx",
    period: "Apr 2021 \u2013 Oct 2021",
    current: false,
    focus: "Cross-Functional Execution",
    description: "Owned the full recruitment lifecycle for the US Delivery Center. Collaborated with leadership and hiring managers on a strategic recruiting process; used JobDiva to manage workflow tracking and ensure data accuracy across the funnel.",
    tags: ["Lifecycle Ownership", "Stakeholder Alignment", "ATS Workflows"]
  },
  {
    role: "Talent Acquisition Lead",
    company: "Rang Technologies",
    period: "Mar 2017 \u2013 Apr 2021",
    current: false,
    focus: "Enterprise Delivery",
    description: "Owned end-to-end delivery on Direct, VMS, and MSP client accounts. Built proactive candidate pipelines, defined requirements with BDMs, and gained platform familiarity through ServiceNow ecosystem recruiting \u2014 ITSM concepts, enterprise workflows, and user roles.",
    tags: ["Pipeline Architecture", "ServiceNow Exposure", "Enterprise Ops"]
  }
];
var skills = [
  {
    id: "product",
    title: "Product & Delivery",
    description: "Product lifecycle, backlog management, requirement definition, Agile execution, stakeholder alignment.",
    tags: ["Roadmapping", "Scrum", "RICE", "Backlog"],
    frameworks: ["RICE / MoSCoW", "Opportunity Solution Tree"],
    tools: ["Jira", "Linear", "Notion"]
  },
  {
    id: "ops",
    title: "Operations & Systems",
    description: "Workflow design, process optimization, platform ownership, KPI tracking, data quality.",
    tags: ["Six Sigma", "Process Design", "SLAs", "Capacity"],
    frameworks: ["Lean Six Sigma", "Capacity Planning"],
    tools: ["Excel", "ATS Platforms", "ServiceNow (exposure)"]
  },
  {
    id: "data",
    title: "Data & Analytics",
    description: "Defining metrics, building dashboards, funnel analysis, data-informed decisions.",
    tags: ["KPIs", "Dashboards", "Revenue Ops"],
    frameworks: ["North Star Metric", "Funnel Analysis"],
    tools: ["Excel", "Google Sheets", "Tableau"]
  },
  {
    id: "tools",
    title: "Tools & Platforms",
    description: "ServiceNow (platform exposure), Lovable, Figma, Notion, data and reporting tools.",
    tags: ["ServiceNow", "Lovable", "Figma", "Notion"],
    frameworks: ["No-Code/Low-Code", "ITSM Familiarity"],
    tools: ["ServiceNow (domain)", "Lovable", "Figma", "Notion"]
  }
];
var projects = [
  {
    title: "AI-First Web Portfolio",
    category: "Rapid Prototyping",
    period: "2025",
    description: "MVP portfolio deployed in 48 hours using AI-assisted development. Demonstrates product thinking and execution speed.",
    tags: ["Lovable", "AI Tools", "Rapid Execution"],
    caseStudy: {
      problem: "Traditional development creates lag between product vision and execution. Needed to demonstrate both PM thinking and shipping ability.",
      solution: "Used Lovable.dev and natural language prompting to build a production-ready portfolio. Owned information architecture, content strategy, and iterative refinement.",
      outcome: "Working product showcasing systems thinking, prioritization, and execution speed."
    }
  },
  {
    title: "Internal ATS Platform Ownership",
    category: "Product Operations",
    period: "2021 \u2013 Present",
    description: "End-to-end ownership of internal SaaS platform. User feedback loops, KPI definition, workflow optimization.",
    tags: ["Platform Ownership", "Backlog", "Configuration"],
    caseStudy: {
      problem: "Operational bottlenecks and data inconsistencies. Users had workarounds bypassing the system.",
      solution: "Took platform ownership, established feedback mechanisms, defined metrics aligning user behavior with business goals.",
      outcome: "Reliable data environment. Reduced workarounds by making the system work for users."
    }
  },
  {
    title: "Revenue Intelligence Dashboards",
    category: "Data & Analytics",
    period: "2022 \u2013 Present",
    description: "Built revenue reports and growth projections identifying leakages. Enabled proactive decision-making.",
    tags: ["Dashboards", "KPIs", "Business Intelligence"],
    caseStudy: {
      problem: "Stakeholders lacked visibility into real-time trends. Revenue leakages undetected until quarter-end.",
      solution: "Designed dynamic revenue reports with clear visualizations and projection matrices for proactive decisions.",
      outcome: "Leadership identified leakages in real-time and took corrective actions."
    }
  },
  {
    title: "Team Gamification & Retention",
    category: "Behavioral Design",
    period: "2021 \u2013 Present",
    description: "Designed incentive plans and retention roadmaps. Reduced attrition and drove performance metrics.",
    tags: ["Incentive Design", "Retention", "Performance"],
    caseStudy: {
      problem: "Performance plateaus and attrition risk across the delivery team.",
      solution: "Designed gamified incentive structures and retention roadmaps tied to measurable delivery outcomes.",
      outcome: "Improved performance metrics and lower attrition."
    }
  }
];

// src/lib/mcp/tools/get-profile.ts
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Get profile",
  description: "Get Sanket Tamboli's professional profile: current role, positioning, summary, certifications, and resume link.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(profile, null, 2) }],
    structuredContent: { profile }
  })
});

// src/lib/mcp/tools/list-experience.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
var list_experience_default = defineTool2({
  name: "list_experience",
  title: "List work experience",
  description: "List the work history timeline (role, company, period, description, focus areas). Optionally return only the current role.",
  inputSchema: {
    currentOnly: z.boolean().optional().describe("When true, return only the current role.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ currentOnly }) => {
    const roles = currentOnly ? experience.filter((e) => e.current) : experience;
    return {
      content: [{ type: "text", text: JSON.stringify(roles, null, 2) }],
      structuredContent: { roles }
    };
  }
});

// src/lib/mcp/tools/list-skills.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
var list_skills_default = defineTool3({
  name: "list_skills",
  title: "List skills and expertise",
  description: "List competency clusters (product & delivery, operations, data, tools) with frameworks and tooling.",
  inputSchema: {
    category: z2.string().optional().describe("Optional cluster id or title fragment to filter by, e.g. 'data'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category }) => {
    const needle = category?.trim().toLowerCase();
    const clusters = needle ? skills.filter(
      (s) => s.id.includes(needle) || s.title.toLowerCase().includes(needle)
    ) : skills;
    return {
      content: [{ type: "text", text: JSON.stringify(clusters, null, 2) }],
      structuredContent: { clusters }
    };
  }
});

// src/lib/mcp/tools/list-projects.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_projects_default = defineTool4({
  name: "list_projects",
  title: "List projects and case studies",
  description: "List portfolio projects with their case studies (problem, solution, outcome). Optionally filter by title or category.",
  inputSchema: {
    query: z3.string().optional().describe("Optional text to match against project title, category, or tags.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ query }) => {
    const needle = query?.trim().toLowerCase();
    const items = needle ? projects.filter(
      (p) => [p.title, p.category, ...p.tags].join(" ").toLowerCase().includes(needle)
    ) : projects;
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { projects: items }
    };
  }
});

// src/lib/mcp/tools/get-contact.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_contact_default = defineTool5({
  name: "get_contact",
  title: "Get contact details",
  description: "Get contact details for Sanket Tamboli: email, phone, LinkedIn, and location.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(contact, null, 2) }],
    structuredContent: { contact }
  })
});

// src/lib/mcp/index.ts
var projectRef = "uhdzxhtlxkhqzrjxhfsq";
var mcp_default = defineMcp({
  name: "sanket-tamboli-portfolio",
  title: "Sanket Tamboli \u2014 Portfolio",
  version: "0.1.0",
  instructions: "Tools for Sanket Tamboli's product-management portfolio. Use `get_profile` for positioning and summary, `list_experience` for the work timeline, `list_skills` for competency clusters, `list_projects` for case studies, and `get_contact` for reaching out.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_profile_default,
    list_experience_default,
    list_skills_default,
    list_projects_default,
    get_contact_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
