// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/get-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/portfolio.ts
var profile = {
  name: "Sanket Tamboli",
  title: "Technology Delivery & Product Operations Leader",
  company: "Technocore360",
  location: "Vadodara, Gujarat, India",
  education: "Postgraduate in HRM",
  yearsOfExperience: 9,
  certifications: [
    "18 ServiceNow micro and suite certifications",
    "Salesforce Agentblazer Champion 2026",
    "36 Salesforce Trailhead badges",
    "AI Product Management",
    "Scrum Master",
    "Lean Six Sigma"
  ],
  summary: "Delivery Director at Technocore360 with 9+ years in technology delivery and product operations. Leads an 11-person India/U.S. team to SLA and fulfillment targets for clients up to Fortune 200 enterprises. Delivers ServiceNow SOW engagements across ITSM, ITOM, GRC, HRSD, CSM, and CMDB workflows, deploying 20+ consultants and reducing niche-role time-to-fill from 90 to 15 days. Acts as internal product owner for SaaS/ATS workflows through user feedback, vendor enhancement prioritization, release validation, and data governance. Defines delivery KPIs and revenue dashboards that guide leadership decisions.",
  positioning: "Technology delivery and product operations leader combining program execution, internal platform ownership, and enterprise workflow expertise.",
  resumeUrl: "https://drive.google.com/file/d/1Ms4HBfit_oIq0Qh32IkQ-p-vMc21ly18/view?usp=drive_link"
};
var contact = {
  email: "sanket.130410111098@gmail.com",
  phone: "+91 9998271731",
  linkedin: "https://linkedin.com/in/sanket-tamboli",
  location: "Vadodara, Gujarat, India"
};
var experience = [
  {
    role: "Delivery Director",
    company: "Technocore360",
    period: "Apr 2026 \u2013 Present",
    current: true,
    focus: "Portfolio Owner",
    description: "Own end-to-end client-services delivery, leading an 11-person India/U.S. team to SLA and fulfillment targets for clients up to Fortune 200 enterprises. Scope ServiceNow SOW roles across ITSM, ITOM, GRC, HRSD, and CSM; deployed 20+ consultants and cut niche-role time-to-fill from 90 to 15 days. Define delivery KPIs, manage executive stakeholders and vendors, and mentor team leads.",
    tags: ["ServiceNow SOW", "Portfolio Leadership", "KPIs & Governance"]
  },
  {
    role: "Senior Manager \u2014 Operations & Delivery",
    company: "Technocore360",
    period: "Apr 2025 \u2013 Mar 2026",
    current: false,
    focus: "Operations Leader",
    description: "Managed daily operations and capacity planning for a 5\u20137 person India/U.S. team with 24/7 coverage. Built revenue matrices and growth dashboards, owned ATS configuration and data standards, advised hiring managers on requirement feasibility, and designed retention and mentorship frameworks.",
    tags: ["Capacity Planning", "Revenue Dashboards", "ATS Governance"]
  },
  {
    role: "Associate Delivery Manager",
    company: "Technocore360",
    period: "Apr 2022 \u2013 Mar 2025",
    current: false,
    focus: "Team Lead",
    description: "Led delivery for Fortune 500 clients and start-ups across ServiceNow SOW, IT, non-IT, healthcare, pharma, and life sciences roles, managing a 10-member team. Acted as internal product owner for SaaS/ATS workflows by gathering feedback, prioritizing vendor enhancements, validating releases, and setting data-governance standards.",
    tags: ["Internal Product Owner", "Release Validation", "Team Leadership"]
  },
  {
    role: "Team Lead Recruitment",
    company: "Technocore360",
    period: "Oct 2021 \u2013 Mar 2022",
    current: false,
    focus: "Resourcing Lead",
    description: "Led business-aligned resourcing professionals across ServiceNow SOW and broader technology and life-sciences roles. Tracked hiring metrics, introduced sourcing methods, evaluated recruitment software, and forecast hiring needs with department managers.",
    tags: ["Resource Planning", "Hiring Analytics", "Software Evaluation"]
  },
  {
    role: "Lead Recruitment Executive",
    company: "Diverse Lynx",
    period: "Apr 2021 \u2013 Oct 2021",
    current: false,
    focus: "Cross-Functional Execution",
    description: "Owned the full recruitment lifecycle for the US Delivery Center. Collaborated with leadership and hiring managers on a strategic recruiting process; used JobDiva to manage workflow tracking and ensure data accuracy across the funnel.",
    tags: ["Lifecycle Ownership", "Stakeholder Alignment", "ATS Workflows"]
  },
  {
    role: "Talent Acquisition Lead",
    company: "Rang Technologies Inc",
    period: "Apr 2019 \u2013 Mar 2021",
    current: false,
    focus: "Award-Winning Lead",
    description: "Trained and mentored recruiters, deployed resources across client requirements, and partnered with Business Development on assigned client relationships. Earned the Striker Award 2019 and a Loyalty Award.",
    tags: ["Mentoring", "Client Relationships", "Striker Award"]
  },
  {
    role: "Talent Acquisition Specialist",
    company: "Rang Technologies Inc",
    period: "Mar 2017 \u2013 Apr 2019",
    current: false,
    focus: "Top Performer",
    description: "Managed full-lifecycle U.S. recruiting across IT, non-IT, healthcare, Salesforce, and insurance for enterprise clients. Earned the Flare 2018 Money Maker Award runner-up for the company's second-highest gross profit.",
    tags: ["Enterprise Recruiting", "Offer Negotiation", "Revenue Performance"]
  }
];
var skills = [
  {
    id: "product",
    title: "Product Operations & Agile",
    description: "Internal product ownership, requirement prioritization, feedback loops, release validation, and Agile execution.",
    tags: ["Product Ownership", "Scrum", "Kanban", "Release Validation"],
    frameworks: ["Scrum / Kanban", "Feedback Loops"],
    tools: ["ATS Platforms", "Figma", "Notion", "Lovable"]
  },
  {
    id: "ops",
    title: "Delivery & Program Leadership",
    description: "Program delivery, SLA management, capacity planning, change management, and cross-functional leadership.",
    tags: ["Program Delivery", "SLAs", "Capacity", "Change Management"],
    frameworks: ["SLA Management", "Capacity Planning"],
    tools: ["Excel", "JobDiva", "Ceipal", "ServiceNow"]
  },
  {
    id: "data",
    title: "Governance & Analytics",
    description: "Delivery KPIs, dashboards, data governance, forecasting, and data-informed decisions.",
    tags: ["KPIs", "Dashboards", "Data Governance", "Forecasting"],
    frameworks: ["Delivery KPIs", "Revenue Analysis"],
    tools: ["Microsoft Excel", "ATS Reporting", "Data Analysis"]
  },
  {
    id: "tools",
    title: "ServiceNow & AI Platforms",
    description: "ServiceNow enterprise workflows, Salesforce Agentforce, ATS ecosystems, and generative AI tools.",
    tags: ["ServiceNow", "Agentforce", "ATS", "Generative AI"],
    frameworks: ["Enterprise Workflow", "Agentic AI"],
    tools: ["ServiceNow", "Salesforce Agentforce", "JobDiva", "Ceipal", "Lovable"]
  }
];
var projects = [
  {
    title: "AI-First Web Portfolio",
    category: "Rapid Prototyping",
    period: "2025 \u2013 Present",
    description: "Responsive React portfolio designed and deployed in under 48 hours through an AI-assisted feedback loop.",
    tags: ["Lovable", "React", "Tailwind CSS"],
    caseStudy: {
      problem: "Traditional development creates lag between product vision and execution. Needed to demonstrate both PM thinking and shipping ability.",
      solution: "Used Lovable.dev, React, Tailwind CSS, and Vite to build the portfolio, iterating UI and content through a generative-AI feedback loop.",
      outcome: "Working product showcasing systems thinking, prioritization, and execution speed."
    }
  },
  {
    title: "SaaS/ATS Product Ownership",
    category: "Product Operations",
    period: "2021 \u2013 Present",
    description: "Internal product ownership spanning user feedback, vendor enhancements, release validation, and data governance.",
    tags: ["Product Operations", "Release Validation", "Data Governance"],
    caseStudy: {
      problem: "Operational bottlenecks and data inconsistencies. Users had workarounds bypassing the system.",
      solution: "Gathered user feedback, prioritized enhancements with vendors, validated releases, and set data-governance standards.",
      outcome: "Improved forecasting accuracy and operational reporting through cleaner workflows and data."
    }
  },
  {
    title: "Delivery KPI & Revenue Dashboards",
    category: "Data & Analytics",
    period: "2022 \u2013 Present",
    description: "Built delivery and revenue dashboards tracking fill rate, ramp time, SLA adherence, leakage, and growth opportunities.",
    tags: ["Delivery KPIs", "Revenue Analysis", "Leadership Reporting"],
    caseStudy: {
      problem: "Stakeholders lacked visibility into real-time trends. Revenue leakages undetected until quarter-end.",
      solution: "Defined delivery KPIs and built revenue matrices, growth dashboards, and projection views for leadership.",
      outcome: "Leadership identified leakages in real-time and took corrective actions."
    }
  },
  {
    title: "ServiceNow SOW Delivery",
    category: "Enterprise Delivery",
    period: "2022 \u2013 Present",
    description: "Translated fixed SOW outcomes into phased plans for niche ServiceNow roles across major workflow domains.",
    tags: ["ServiceNow", "SOW", "Program Delivery"],
    caseStudy: {
      problem: "Niche ServiceNow requirements were taking up to 90 days to fill, creating delivery risk against fixed milestones.",
      solution: "Scoped role requirements against deliverables and milestones, then converted scope into prioritized phased hiring plans.",
      outcome: "Deployed 20+ consultants and reduced niche-role time-to-fill from 90 to 15 days."
    }
  }
];

// src/lib/mcp/tools/get-profile.ts
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Get profile",
  description: "Get Sanket Tamboli's professional profile: current role, positioning, summary, certifications, and resume link.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(profile, null, 2) }],
    structuredContent: { profile }
  })
});

// src/lib/mcp/tools/list-experience.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
var list_experience_default = defineTool2({
  name: "list_experience",
  title: "List work experience",
  description: "List the work history timeline (role, company, period, description, focus areas). Optionally return only the current role.",
  inputSchema: {
    currentOnly: z.boolean().optional().describe("When true, return only the current role.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ currentOnly }) => {
    const roles = currentOnly ? experience.filter((e) => e.current) : experience;
    return {
      content: [{ type: "text", text: JSON.stringify(roles, null, 2) }],
      structuredContent: { roles }
    };
  }
});

// src/lib/mcp/tools/list-skills.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
var list_skills_default = defineTool3({
  name: "list_skills",
  title: "List skills and expertise",
  description: "List competency clusters (product & delivery, operations, data, tools) with frameworks and tooling.",
  inputSchema: {
    category: z2.string().optional().describe("Optional cluster id or title fragment to filter by, e.g. 'data'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category }) => {
    const needle = category?.trim().toLowerCase();
    const clusters = needle ? skills.filter(
      (s) => s.id.includes(needle) || s.title.toLowerCase().includes(needle)
    ) : skills;
    return {
      content: [{ type: "text", text: JSON.stringify(clusters, null, 2) }],
      structuredContent: { clusters }
    };
  }
});

// src/lib/mcp/tools/list-projects.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_projects_default = defineTool4({
  name: "list_projects",
  title: "List projects and case studies",
  description: "List portfolio projects with their case studies (problem, solution, outcome). Optionally filter by title or category.",
  inputSchema: {
    query: z3.string().optional().describe("Optional text to match against project title, category, or tags.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ query }) => {
    const needle = query?.trim().toLowerCase();
    const items = needle ? projects.filter(
      (p) => [p.title, p.category, ...p.tags].join(" ").toLowerCase().includes(needle)
    ) : projects;
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { projects: items }
    };
  }
});

// src/lib/mcp/tools/get-contact.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_contact_default = defineTool5({
  name: "get_contact",
  title: "Get contact details",
  description: "Get contact details for Sanket Tamboli: email, phone, LinkedIn, and location.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(contact, null, 2) }],
    structuredContent: { contact }
  })
});

// src/lib/mcp/index.ts
var projectRef = "uhdzxhtlxkhqzrjxhfsq";
var mcp_default = defineMcp({
  name: "sanket-tamboli-portfolio",
  title: "Sanket Tamboli \u2014 Portfolio",
  version: "0.1.0",
  instructions: "Tools for Sanket Tamboli's product-management portfolio. Use `get_profile` for positioning and summary, `list_experience` for the work timeline, `list_skills` for competency clusters, `list_projects` for case studies, and `get_contact` for reaching out.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_profile_default,
    list_experience_default,
    list_skills_default,
    list_projects_default,
    get_contact_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
